language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


before_script:
 # - npm install -g gulp
  - chmod 777 ./node_modules

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "xiajunyi"
  - git config user.email "309292581@qq.com"
  - git add .
  - git commit -m "docs:update articles"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/xiajunyi/xiajunyi.github.io.git
